services:
  inventory-service:
    build:
      context: ./inventory
      dockerfile: src/main/docker/Dockerfile
      args:
        JAR_FILE: inventory-1.0-SNAPSHOT.jar
        PROJECT_NAME: inventory
        PROJECT: counterly.springframework:inventory:1.0-SNAPSHOT
    ports:
      - "8081:8081"
    container_name: inventory-service

  order-service:
    build:
      context: ./order
      dockerfile: src/main/docker/Dockerfile
      args:
        JAR_FILE: counterly.order-1.0-SNAPSHOT.jar
        PROJECT_NAME: counterly.order
        PROJECT: counterly.springframework:counterly.order:1.0-SNAPSHOT
    ports:
      - "8082:8082"
    container_name: order-service
