server:
  port: 8086

spring:
  application:
    name: product-service
  config:
    import: "configserver:http://localhost:8888/"

  cloud:
    config:
      username: username
      password: password